name: Basic CI

on:
  # pull_request:
  push:
    branchs: [ develop ] #it is a syntax
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -name: Run build
      run: echo "CI is running" 